"""add sync states table

Revision ID: add_sync_states_table
Revises: 89298658ab73
Create Date: 2024-03-21 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_sync_states_table'
down_revision: Union[str, None] = '89298658ab73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sync_states',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('client_id', sa.String(), nullable=False, index=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('user.id'), nullable=False, index=True),
        sa.Column('entity_type', sa.String(), nullable=False, index=True),
        sa.Column('last_sync_version', sa.Integer(), nullable=False, default=0),
        sa.Column('last_sync_timestamp', sa.DateTime(), nullable=False),
        sa.Column('sync_token', sa.String(), nullable=True, index=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_states')
    # ### end Alembic commands ### 